const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Shirt',
            category: 'Shirts',
            image: '/images/p1.jpeg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id: '2',
            name: 'Adidas Shirt',
            category: 'Shirts',
            image: '/images/p2.jpeg',
            price: 100,
            countInStock: 15,
            brand: 'Adidas',
            rating: 4,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            _id: '3',
            name: 'Lacoste Shirt',
            category: 'Shirts',
            image: '/images/p3.jpeg',
            price: 120,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 3.5,
            numReviews: 3,
            description: 'High Quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Shirt',
            category: 'Pants',
            image: '/images/p4.jpeg',
            price: 130,
            countInStock: 5,
            brand: 'Nike',
            rating: 4,
            numReviews: 5,
            description: 'High Quality product',
        },
        {
            _id: '5',
            name: 'Puma slim pants',
            category: 'Pants',
            image: '/images/p5.jpeg',
            price: 120,
            countInStock: 30,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality product',
        },
    ]
}

export default data;