import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: "chandru",
            email: "chandru@xyz.com",
            password: bcrypt.hashSync('12345', 8),
            isAdmin: true,
        },
        {
            name: "ram",
            email: "ram@xyz.com",
            password: bcrypt.hashSync('12345', 8),
            isAdmin: false,
        }
    ],
    products: [
        {
            name: 'Nike Shirt',
            category: 'Shirts',
            image: '/images/p1.jpeg',
            price: 150,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            name: 'Adidas Shirt',
            category: 'Shirts',
            image: '/images/p2.jpeg',
            price: 100,
            countInStock: 15,
            brand: 'Adidas',
            rating: 4,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            name: 'Lacoste Shirt',
            category: 'Shirts',
            image: '/images/p3.jpeg',
            price: 120,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 3.5,
            numReviews: 3,
            description: 'High Quality product',
        },
        {
            name: 'Nike Slim Shirt',
            category: 'Pants',
            image: '/images/p4.jpeg',
            price: 130,
            countInStock: 5,
            brand: 'Nike',
            rating: 4,
            numReviews: 5,
            description: 'High Quality product',
        },
        {
            name: 'Puma slim pants',
            category: 'Pants',
            image: '/images/p5.jpeg',
            price: 120,
            countInStock: 30,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            name: 'Nike Shirts',
            category: 'Shirts',
            image: '/images/p1.jpeg',
            price: 150,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            name: 'Adidas Shirts',
            category: 'Shirts',
            image: '/images/p2.jpeg',
            price: 100,
            countInStock: 15,
            brand: 'Adidas',
            rating: 4,
            numReviews: 10,
            description: 'High Quality product',
        },
        {
            name: 'Lacoste Shirts',
            category: 'Shirts',
            image: '/images/p3.jpeg',
            price: 120,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 3.5,
            numReviews: 3,
            description: 'High Quality product',
        },
        {
            name: 'Nike Slim Shirts',
            category: 'Pants',
            image: '/images/p4.jpeg',
            price: 130,
            countInStock: 5,
            brand: 'Nike',
            rating: 4,
            numReviews: 5,
            description: 'High Quality product',
        },
        {
            name: 'Puma slim pant',
            category: 'Pants',
            image: '/images/p5.jpeg',
            price: 120,
            countInStock: 30,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality product',
        },
    ]
}

export default data;